# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'RxDataSourceCollectionViewExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxDataSourceCollectionViewExample
  pod 'EasyTipView', '~> 2.1'
  pod 'ActiveLabel'
  pod 'Cosmos', '~> 23.0'

  target 'RxDataSourceCollectionViewExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxDataSourceCollectionViewExampleUITests' do
    # Pods for testing
  end

end
